name: SARS2_RBD_Ab_escape_maps
channels:
  - bioconda
  - conda-forge
  - defaults

dependencies:
  - altair=4.1
  - altair_saver=0.5
  - jupyterlab=3.0.7
  - nodejs
  - ruamel.yaml=0.16
  - pandas=1.2.1
  - pip
  - python=3.8
  - scikit-learn=0.24.1
  - vega_datasets=0.9
  - pip:
    - dms_variants==0.8.6
